INSERT INTO USERS (ID, USERNAME, PASSWORD, enabled) VALUES (0, 'root', 's3cret', true);
INSERT INTO AUTHORITIES (AUTHORITY, USERNAME) VALUES ('ADMIN', 'root');

insert into post (id, title, content, timestamp) values (0, 0, 'CN Sucks.', 4096);
insert into post (id, title, content, timestamp) values (1, 1, 'CN Sucks.', 4097);
insert into post (id, title, content, timestamp) values (2, 2, 'CN Sucks.', 4098);
insert into post (id, title, content, timestamp) values (3, 3, 'CN Sucks.', 4099);
insert into post (id, title, content, timestamp) values (4, 4, 'CN Sucks.', 4100);
insert into post (id, title, content, timestamp) values (5, 5, 'CN Sucks.', 4101);
insert into post (id, title, content, timestamp) values (6, 6, 'CN Sucks.', 4102);
insert into post (id, title, content, timestamp) values (7, 7, 'CN Sucks.', 4103);
insert into post (id, title, content, timestamp) values (8, 8, 'CN Sucks.', 4104);
insert into post (id, title, content, timestamp) values (9, 9, 'CN Sucks.', 4105);
insert into post (id, title, content, timestamp) values (10, 10, 'CN Sucks.', 4106);
insert into post (id, title, content, timestamp) values (11, 11, 'CN Sucks.', 4107);
insert into post (id, title, content, timestamp) values (12, 12, 'CN Sucks.', 4108);
insert into post (id, title, content, timestamp) values (13, 13, 'CN Sucks.', 4109);
insert into post (id, title, content, timestamp) values (14, 14, 'CN Sucks.', 4110);
insert into post (id, title, content, timestamp) values (15, 15, 'CN Sucks.', 4111);
insert into post (id, title, content, timestamp) values (16, 16, 'CN Sucks.', 4112);
insert into post (id, title, content, timestamp) values (17, 17, 'CN Sucks.', 4113);
insert into post (id, title, content, timestamp) values (18, 18, 'CN Sucks.', 4114);
insert into post (id, title, content, timestamp) values (19, 19, 'CN Sucks.', 4115);
insert into post (id, title, content, timestamp) values (20, 20, 'CN Sucks.', 4116);
insert into post (id, title, content, timestamp) values (21, 21, 'CN Sucks.', 4117);
insert into post (id, title, content, timestamp) values (22, 22, 'CN Sucks.', 4118);
insert into post (id, title, content, timestamp) values (23, 23, 'CN Sucks.', 4119);
insert into post (id, title, content, timestamp) values (24, 24, 'CN Sucks.', 4120);
insert into post (id, title, content, timestamp) values (25, 25, 'CN Sucks.', 4121);
insert into post (id, title, content, timestamp) values (26, 26, 'CN Sucks.', 4122);
insert into post (id, title, content, timestamp) values (27, 27, 'CN Sucks.', 4123);
insert into post (id, title, content, timestamp) values (28, 28, 'CN Sucks.', 4124);
insert into post (id, title, content, timestamp) values (29, 29, 'CN Sucks.', 4125);
insert into post (id, title, content, timestamp) values (30, 30, 'CN Sucks.', 4126);
insert into post (id, title, content, timestamp) values (31, 31, 'CN Sucks.', 4127);
insert into post (id, title, content, timestamp) values (32, 32, 'CN Sucks.', 4128);

insert into Comments (id, content, timestamp, belongto) values (0, 'Sleepy Now.', 34753, 4096);
insert into Comments (id, content, timestamp, belongto) values (1, 'Sleepy Now.', 34754, 4096);
insert into Comments (id, content, timestamp, belongto) values (2, 'Sleepy Now.', 34755, 4096);
insert into Comments (id, content, timestamp, belongto) values (3, 'Sleepy Now.', 34757, 4096);
