DROP TABLE USERS IF EXISTS;
CREATE TABLE PUBLIC.USERS(ENABLED BOOLEAN,NICKNAME VARCHAR(255),PASSWORD VARCHAR(255),USERNAME VARCHAR(255));

DROP TABLE authorities IF EXISTS;
CREATE TABLE PUBLIC.authorities(authority VARCHAR(255),USERNAME VARCHAR(255));
